version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
    NODE_OPTIONS: "--max_old_space_size=8192"
    
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Entered the install phase...
      - npm install yarn -g
      - echo "\n ======== installing client dependencies ======== \n"
      - cd client && yarn install
    finally:
      - echo This always runs even if the update or install command fails
      - echo "returning to root project directory"
      - cd ..
  pre_build:
    commands:
      - echo Entered the pre_build phase...
    finally:
      - echo This always runs even if the login command fails 
  build:
    commands:
      - echo Entered the build phase...
      # set env var to increase node max heap memory size (V8 flag)
      - export NODE_OPTIONS=--max_old_space_size=16384
      - echo $NODE_OPTIONS
      - echo "\n ======== Building client static assets... ========"
      - echo "Build started on $(date)\n"
      - cd ./client && yarn run build
      # run i18n builds in parallel with "&"
      # waiting for all jobs to finish with "wait" command
      - yarn run build-i18n:en & yarn run build-i18n:es & yarn run build-i18n:fr & yarn run build-i18n:jp & wait
    finally:
      - echo This always runs even if the install command fails
      # check that client build folder exists
      - $([ -d "./dist/client" ])
      - cd ..
  post_build:
    commands:
      - echo Entered the post_build phase...
      - mkdir ./client_built
      - cp -R ./client/dist/client/* ./client_built
      - rm -rf ./client
      - mv ./client_built ./client
      # check that the translations folders exist
      - $([ -d "./client/en" ])
      - $([ -d "./client/es" ])
      - $([ -d "./client/fr" ])
      - $([ -d "./client/jp" ])
      - echo "\n ======== Build completed on $(date) ======== \n"

artifacts:
  files:
    - 'client/**/*'
  name: roodeo-scalable-assets
